import { Resident } from './types';

export const mockResidents: Resident[] = [
  {
    id: '1',
    name: 'Eleanor Vance',
    room: 'Room 201',
    avatarUrl: 'https://i.pravatar.cc/150?u=eleanor',
    statusColor: 'green',
    bathStatus: 'done',
    mealStatus: 'eaten',
    toiletStatus: 'independent',
    careMinutesToday: 180,
    careMinutesTarget: 200,
  },
  {
    id: '2',
    name: 'Arthur Pendelton',
    room: 'Room 205',
    avatarUrl: 'https://i.pravatar.cc/150?u=arthur',
    statusColor: 'yellow',
    bathStatus: 'due',
    mealStatus: 'assisted',
    toiletStatus: 'pad-change',
    careMinutesToday: 120,
    careMinutesTarget: 250,
  },
  {
    id: '3',
    name: 'Chen Wei',
    room: 'Room 110',
    avatarUrl: 'https://i.pravatar.cc/150?u=chen',
    statusColor: 'red',
    bathStatus: 'overdue',
    mealStatus: 'missed',
    toiletStatus: 'assisted',
    careMinutesToday: 45,
    careMinutesTarget: 300,
  },
  {
    id: '4',
    name: 'Margaret Smith',
    room: 'Room 112',
    avatarUrl: 'https://i.pravatar.cc/150?u=margaret',
    statusColor: 'green',
    bathStatus: 'done',
    mealStatus: 'eaten',
    toiletStatus: 'assisted',
    careMinutesToday: 210,
    careMinutesTarget: 210,
  },
  {
    id: '5',
    name: 'James O\'Connor',
    room: 'Room 304',
    avatarUrl: 'https://i.pravatar.cc/150?u=james',
    statusColor: 'yellow',
    bathStatus: 'due',
    mealStatus: 'eaten',
    toiletStatus: 'independent',
    careMinutesToday: 90,
    careMinutesTarget: 180,
  },
  {
    id: '6',
    name: 'Betty White',
    room: 'Room 306',
    avatarUrl: 'https://i.pravatar.cc/150?u=betty',
    statusColor: 'green',
    bathStatus: 'done',
    mealStatus: 'eaten',
    toiletStatus: 'independent',
    careMinutesToday: 150,
    careMinutesTarget: 150,
  }
];
