import { Resident } from "./types";

export const mockResidents: Resident[] = [
  {
    id: "1",
    name: "Eleanor Vance",
    room: "Room 201",
    avatarUrl: "https://i.pravatar.cc/150?u=eleanor",
    statusColor: "green",
    bathStatus: "done",
    mealStatus: "eaten",
    toiletStatus: "independent",
    careMinutesToday: 180,
    careMinutesTarget: 200,
  },
  {
    id: "2",
    name: "Arthur Pendelton",
    room: "Room 205",
    avatarUrl: "https://i.pravatar.cc/150?u=arthur",
    statusColor: "yellow",
    bathStatus: "due",
    mealStatus: "assisted",
    toiletStatus: "pad-change",
    careMinutesToday: 120,
    careMinutesTarget: 250,
  },
  {
    id: "3",
    name: "Chen Wei",
    room: "Room 110",
    avatarUrl: "https://i.pravatar.cc/150?u=chen",
    statusColor: "red",
    bathStatus: "overdue",
    mealStatus: "missed",
    toiletStatus: "assisted",
    careMinutesToday: 45,
    careMinutesTarget: 300,
  },
  {
    id: "4",
    name: "Margaret Smith",
    room: "Room 112",
    avatarUrl: "https://i.pravatar.cc/150?u=margaret",
    statusColor: "green",
    bathStatus: "done",
    mealStatus: "eaten",
    toiletStatus: "assisted",
    careMinutesToday: 210,
    careMinutesTarget: 210,
  },
  {
    id: "5",
    name: "James O'Connor",
    room: "Room 304",
    avatarUrl: "https://i.pravatar.cc/150?u=james",
    statusColor: "yellow",
    bathStatus: "due",
    mealStatus: "eaten",
    toiletStatus: "independent",
    careMinutesToday: 90,
    careMinutesTarget: 180,
  },
  {
    id: "6",
    name: "Betty White",
    room: "Room 306",
    avatarUrl: "https://i.pravatar.cc/150?u=betty",
    statusColor: "green",
    bathStatus: "done",
    mealStatus: "eaten",
    toiletStatus: "independent",
    careMinutesToday: 150,
    careMinutesTarget: 150,
  },
];

export const mockRoster: any[] = [
  {
    id: "1",
    day: "Monday",
    shiftType: "Day",
    time: "07:00 - 15:00",
    rnCount: 3,
    pwCount: 15,
  },
  {
    id: "2",
    day: "Monday",
    shiftType: "Evening",
    time: "15:00 - 23:00",
    rnCount: 2,
    pwCount: 12,
  },
  {
    id: "3",
    day: "Monday",
    shiftType: "Night",
    time: "23:00 - 07:00",
    rnCount: 1,
    pwCount: 6,
  },

  {
    id: "4",
    day: "Tuesday",
    shiftType: "Day",
    time: "07:00 - 15:00",
    rnCount: 3,
    pwCount: 14,
  },
  {
    id: "5",
    day: "Tuesday",
    shiftType: "Evening",
    time: "15:00 - 23:00",
    rnCount: 2,
    pwCount: 12,
  },
  {
    id: "6",
    day: "Tuesday",
    shiftType: "Night",
    time: "23:00 - 07:00",
    rnCount: 1,
    pwCount: 6,
  },

  {
    id: "7",
    day: "Wednesday",
    shiftType: "Day",
    time: "07:00 - 15:00",
    rnCount: 3,
    pwCount: 15,
  },
  {
    id: "8",
    day: "Wednesday",
    shiftType: "Evening",
    time: "15:00 - 23:00",
    rnCount: 2,
    pwCount: 12,
  },
  {
    id: "9",
    day: "Wednesday",
    shiftType: "Night",
    time: "23:00 - 07:00",
    rnCount: 0,
    pwCount: 6,
  },

  {
    id: "10",
    day: "Thursday",
    shiftType: "Day",
    time: "07:00 - 15:00",
    rnCount: 3,
    pwCount: 15,
  },
  {
    id: "11",
    day: "Thursday",
    shiftType: "Evening",
    time: "15:00 - 23:00",
    rnCount: 2,
    pwCount: 12,
  },
  {
    id: "12",
    day: "Thursday",
    shiftType: "Night",
    time: "23:00 - 07:00",
    rnCount: 1,
    pwCount: 6,
  },

  {
    id: "13",
    day: "Friday",
    shiftType: "Day",
    time: "07:00 - 15:00",
    rnCount: 3,
    pwCount: 15,
  },
  {
    id: "14",
    day: "Friday",
    shiftType: "Evening",
    time: "15:00 - 23:00",
    rnCount: 2,
    pwCount: 12,
  },
  {
    id: "15",
    day: "Friday",
    shiftType: "Night",
    time: "23:00 - 07:00",
    rnCount: 1,
    pwCount: 6,
  },

  {
    id: "16",
    day: "Saturday",
    shiftType: "Day",
    time: "07:00 - 15:00",
    rnCount: 2,
    pwCount: 12,
  },
  {
    id: "17",
    day: "Saturday",
    shiftType: "Evening",
    time: "15:00 - 23:00",
    rnCount: 1,
    pwCount: 10,
  },
  {
    id: "18",
    day: "Saturday",
    shiftType: "Night",
    time: "23:00 - 07:00",
    rnCount: 1,
    pwCount: 6,
  },

  {
    id: "19",
    day: "Sunday",
    shiftType: "Day",
    time: "07:00 - 15:00",
    rnCount: 2,
    pwCount: 12,
  },
  {
    id: "20",
    day: "Sunday",
    shiftType: "Evening",
    time: "15:00 - 23:00",
    rnCount: 1,
    pwCount: 10,
  },
  {
    id: "21",
    day: "Sunday",
    shiftType: "Night",
    time: "23:00 - 07:00",
    rnCount: 1,
    pwCount: 6,
  },
];
